select * from customer;
--what is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue from customer group by gender ;

--which customers used a discount but still spent more than the average purchase amount
select customer_id as customer,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>= (select AVG(purchase_amount)
from customer);

--which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating::numeric),2)  from customer 
group by item_purchased 
order by avg(review_rating) desc limit 5;


--compare the average purchase amounts between standard and express shipping
select shipping_type,
round(avg(purchase_amount),2)
from customer 
where shipping_type in ('Standard','Express') group by shipping_type;

--Do subscribed customers spend more?Compare average spend and total revenue between
--subscribers and non-subscribers?
select subscription_status,sum(purchase_amount),
round(avg(purchase_amount),2),count(customer_id) from customer group by subscription_status;

--which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
ROUND(100* sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2)
as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;


--segment customers into New,Returning and Loyal based on their total number of previous
--purchases,show the count of each 
with customer_type as(
select customer_id,previous_purchases,
case
	when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer)

select customer_segment,count(*) as "Number of Customers" 
from customer_type group by customer_segment;


--what are the top 3 most purchased products within each category
with item_count as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased)

select category,item_purchased,total_orders,item_rank from item_count
where item_rank<=3;


--Are customers who are repeat buyers(more than 5 previous purchases) also likely to 
--subscribe?

select count(customer_id),subscription_status from customer
where previous_purchases>5
group by subscription_status;

--what is the revenue contribution of each age group
select age_group,sum(purchase_amount) as total_purchase from customer
group by age_group order by total_purchase desc;

